version: 2.1

executors:
  salesforce-cli:
    docker:
      - image: circleci/node:14  # Use Node.js for Salesforce CLI
    working_directory: ~/project

jobs:
  auth:
    executor: salesforce-cli
    steps:
      - checkout
      - run:
          name: Authenticate with Salesforce
          command: echo $SF_AUTH_URL | sfdx auth:sfdxurl:store -f /dev/stdin -s -a myOrg

  deploy:
    executor: salesforce-cli
    steps:
      - checkout
      - run:
          name: Authenticate with Salesforce
          command: echo $SF_AUTH_URL | sfdx auth:sfdxurl:store -f /dev/stdin -s -a myOrg
      - run:
          name: Deploy Metadata
          command: sfdx force:source:deploy -p force-app -u myOrg --json --loglevel fatal

  test:
    executor: salesforce-cli
    steps:
      - checkout
      - run:
          name: Authenticate with Salesforce
          command: echo $SF_AUTH_URL | sfdx auth:sfdxurl:store -f /dev/stdin -s -a myOrg
      - run:
          name: Run Apex Tests
          command: sfdx force:apex:test:run -u myOrg --wait 10 --resultformat human

workflows:
  version: 2
  deploy_and_
