version: 2.1

executors:
  salesforce-executor:
    docker:
      - image: circleci/node:14  # Using Node.js for Salesforce CLI
    working_directory: ~/project

jobs:
  setup:
    executor: salesforce-executor
    steps:
      - checkout
      - run:
          name: Install Salesforce CLI
          command: |
            curl -fsSL https://developer.salesforce.com/media/salesforce-cli/install.sh | bash
            export PATH=$HOME/.local/bin:$PATH
            sfdx --version
      - run:
          name: Authenticate Dev Hub
          command: |
            echo $SF_AUTH_URL > sfdx_auth_url.txt
            sfdx auth:sfdxurl:store -f sfdx_auth_url.txt -a DevHub
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  create-scratch-org:
    executor: salesforce-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Create Salesforce Scratch Org
          command: |
            sfdx force:org:create -f config/project-scratch-def.json -a ScratchOrg -d 1 -s
            sfdx force:org:display -u ScratchOrg
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy-changes:
    executor: salesforce-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy Changes to Scratch Org
          command: |
            sfdx force:source:push -u ScratchOrg
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  run-tests:
    executor: salesforce-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Apex Tests and Check Coverage
          command: |
            sfdx force:apex:test:run -u ScratchOrg --codecoverage --resultformat human
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  delete-scratch-org:
    executor: salesforce-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Delete Scratch Org
          command: |
            sfdx force:org:delete -u ScratchOrg -p

workflows:
  version: 2
  salesforce-ci-cd:
    jobs:
      - setup
      - create-scratch-org:
          requires:
            - setup
      - deploy-changes:
          requires:
            - create-scratch-org
      - run-tests:
          requires:
            - deploy-changes
      - delete-scratch-org:
          requires:
            - run-tests
