version: 2.1

executors:
  salesforce-executor:
    docker:
      - image: cimg/node:20.8  # Latest Node.js image
    working_directory: ~/project

jobs:
  setup:
    executor: salesforce-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip
      - run:
          name: Install Salesforce CLI
          command: |
            npm install --global sfdx-cli --unsafe-perm=true
            export PATH=~/.npm-global/bin:$PATH
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
      - run:
          name: Verify Installation
          command: |
            which sfdx || echo "sfdx not found"
            sfdx --version
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  create-scratch-org:
    executor: salesforce-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Create Salesforce Scratch Org
          command: |
            source $BASH_ENV
            sfdx force:org:create -f config/project-scratch-def.json -a ScratchOrg -d 1 -s
            sfdx force:org:display -u ScratchOrg
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  version: 2
  salesforce-ci-cd:
    jobs:
      - setup
      - create-scratch-org:
          requires:
            - setup
