version: 2.1

executors:
  salesforce-executor:
    docker:
      - image: cimg/node:20.8  # CircleCI image with Node.js
    working_directory: ~/project

jobs:
  setup:
    executor: salesforce-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip
      - run:
          name: Install Salesforce CLI (Official)
          command: |
            curl -fsSL https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
            ./sfdx/install
            echo 'export PATH=~/sfdx/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            sfdx --version
      - persist_to_workspace:
          root: ~/
          paths:
            - sfdx  # Persist CLI for all jobs
            - project  # Persist project files

  create-scratch-org:
    executor: salesforce-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load Salesforce CLI
          command: |
            export PATH=~/sfdx/bin:$PATH
            source $BASH_ENV
            sfdx --version
      - run:
          name: Create Salesforce Scratch Org
          command: |
            sfdx force:org:create -f project/config/project-scratch-def.json -a ScratchOrg -d 1 -s
            sfdx force:org:display -u ScratchOrg
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy-changes:
    executor: salesforce-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load Salesforce CLI
          command: |
            export PATH=~/sfdx/bin:$PATH
            source $BASH_ENV
      - run:
          name: Deploy Changes to Scratch Org
          command: |
            sfdx force:source:push -u ScratchOrg
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  run-tests:
    executor: salesforce-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load Salesforce CLI
          command: |
            export PATH=~/sfdx/bin:$PATH
            source $BASH_ENV
      - run:
          name: Run Apex Tests and Check Coverage
          command: |
            sfdx force:apex:test:run -u ScratchOrg --codecoverage --resultformat human
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  delete-scratch-org:
    executor: salesforce-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Load Salesforce CLI
          command: |
            export PATH=~/sfdx/bin:$PATH
            source $BASH_ENV
      - run:
          name: Delete Scratch Org
          command: |
            sfdx force:org:delete -u ScratchOrg -p

workflows:
  version: 2
  salesforce-ci-cd:
    jobs:
      - setup
      - create-scratch-org:
          requires:
            - setup
      - deploy-changes:
          requires:
            - create-scratch-org
      - run-tests:
          requires:
            - deploy-changes
      - delete-scratch-org:
          requires:
            - run-tests
